"""align nullability and column lengths with models.py

Revision ID: 2c4ae75686dd
Revises: 49fd33dc99c3
Create Date: 2026-07-10 18:29:59.466300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c4ae75686dd'
down_revision: Union[str, Sequence[str], None] = '49fd33dc99c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'requester_reference',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'P1'::character varying"))
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'request_reference',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'reviewer_reference',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'decision',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('reviews', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'decision',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewer_reference',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'request_reference',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('requests', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'P1'::character varying"))
    op.alter_column('requests', 'requester_reference',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
