"""baseline: initial schema (users, requests, reviews)

Revision ID: 880cf8adb7a1
Revises: 
Create Date: 2026-07-09 20:18:48.928417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880cf8adb7a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.CheckConstraint("role IN ('requester', 'reviewer', 'admin')"),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('requester_reference', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='P1', nullable=True),
    sa.Column('urgency_justification', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=True),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("priority IN ('P0', 'P1', 'P2', 'P3')"),
    sa.CheckConstraint("request_type IN ('hardware', 'software', 'access-request', 'account-password', 'bug-report', 'network', 'onboarding-offboarding', 'facilities', 'other')"),
    sa.CheckConstraint("status IN ('open', 'in-progress', 'resolved', 'closed', 'approved', 'rejected')"),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requester_reference'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('request_reference', sa.Integer(), nullable=True),
    sa.Column('reviewer_reference', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("decision IN ('APPROVED', 'NOT APPROVED')"),
    sa.ForeignKeyConstraint(['request_reference'], ['requests.request_id'], ),
    sa.ForeignKeyConstraint(['reviewer_reference'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('requests')
    op.drop_table('users')
    # ### end Alembic commands ###
