"""add indexes on requests status and created_at

Revision ID: d811a684329c
Revises: 219b7e533423
Create Date: 2026-07-23 12:45:08.240226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd811a684329c'
down_revision: Union[str, Sequence[str], None] = '219b7e533423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    # ### end Alembic commands ###
